### PR TITLE
Add support for repeating a waveform in sync mode.

### PR DESCRIPTION
**Pull request by xtagon**
Hi,

My use case for pigpiox requires the sync mode for waveforms (at least, I think it does!). I'm encoding a CPPM signal to relay to the trainer port of a FrSky Taranis in realtime.

I can handle the CPPM encoding part.

My questions are:

1. Is this PR on the right track? Should this be all that is needed to use sync mode? I'm not very familiar with pigpiod to be honest.
2. What's a good way to test this? I'm not quite sure on the exact behavioral difference for sync mode, but I think it's the way to go for a realtime loop.
3. If I want to send a new 22.5ms frame every 22.5ms, will the Elixir process "keep up" or do I need to be aware of issues with attempting a realtime feed?

Your help is greatly appreciated - and thank you for writing this library! 👍

### CODE REVIEW

**Comment by xtagon** [comment]
@jordan0day Feel free to take a look at this since you expressed interest in the same feature over Slack :-)

**Comment by xtagon** [comment]
Directly related to #2

**Comment by tokafish** [comment]
I honestly don't know enough about pigpiod to answer your first questions, sorry :(  Regarding the last, I do suspect that if you need a guarantee of something happening at exactly 22.5ms, you will probably need to get it to happen within pigpiod, and not Elixir.

**Comment by xtagon** [comment]
I have to send frames in sync every 22.5 ms, but it's perfectly fine to have the same frame repeat for the next frame if the system can't keep up. I'm just not sure I understand if that's the behavior of the wave mode or not. I'll try to figure it out another way.

**Comment by jordan0day** [comment]
I'm afraid to admit I still haven't gotten around to testing this out. Hopefully sometime this week, as I've finally finished to putting together all the hardware bits of my project.

Based on my reading of the pigpio docs and a few forum posts by the pigpio author, I was under the impression the `WAVE_MODE_[ONE_SHOT|REPEAT]_SYNC` essentially "queues" the wave to execute immediately after the current wave has finished. So if you've sent a `WAVE_MODE_REPEAT_SYNC` wave of 22.5ms, it will continue to repeat until you stop the wave or send a new wave, and if you send another one, it will wait until the previous waveform has finished before beginning. (Of course the pigpio docs say something along the lines of "pigpio _tries its best_ to synchronize ..." which doesn't inspire total confidence 😀).

So with your use case, where it sounds like you're essentially relaying a signal, it *seems* like you should be fine to just send 22.5ms waveforms as you get them, with `WAVE_MODE_REPEAT_SYNC`. And pigpio will either replay the previous waveform (if you haven't sent a new one) or begin the new waveform as soon as the previous 22.5ms wave completes.

**Comment by xtagon** [comment]
@jordan0day Thanks for the input!

I _hope_ it works the way you described but I guess the only way to be sure is to do a live test in a couple scenarios and measure.

I am indeed relaying a signal for my use case (mapping various input methods into an RC signal).

**Review by tokafish — APPROVED** [review]

**Pull request merged**
