### PR TITLE
Add support for pigpio's waveform feature

### PR DESCRIPTION
**Pull request by tokafish**
Some example code:

```elixir
gpio = 21

pulses = [%Pigpiox.Waveform.Pulse{gpio_on: gpio, delay: 500000}, %Pigpiox.Waveform.Pulse{gpio_off: gpio, delay: 500000}] 

Pigpiox.Waveform.add_generic(pulses)

{:ok, wave_id} = Pigpiox.Waveform.create()

Pigpiox.GPIO.set_mode(gpio, :output)

Pigpiox.Waveform.repeat(wave_id)
```

### CODE REVIEW

**Comment by tokafish** [comment]
@joelbyler I put together a MVP implementation of waveform support. There's still a few more functions to implement, but I've used the code above to make a LED flash successfully.

This is pretty much a direct port from the python, so I'd love your feedback on what might be better. I was thinking of a builder-style interface, where you might do:

```elixir
Pigpiox.Waveform.Builder.new(21)
  |> on()
  |> delay(500)
  |> off()
  |> delay(500) 
```

The problem with the above is pigpio allows for waveforms that are more sophisticated (turn on/off different GPIO in a single pulse - https://github.com/joan2937/pigpio/blob/master/pigpio.py#L2076, as well as merging multiple calls to add_generic into a single waveform).

I think it would be cool to be able to express the entire waveform as calls to elixir functions, and have the library do the appropriate calls to pigpio. Do you have any ideas?

**Comment by joelbyler** [comment]
@tokafish this looks like some great work.  I think a strait port over from Python is a good way to get things going as well.  And I like your idea of using a builder style interface.  I'm not sure of the `new` function mostly because that reminds me so much of ruby and oop, ;)  but I'm not sure what else you would call that function, maybe `start`? (shrug)  Overall this is great work and I really appreciate you taking my feedback on this idea and adding the wave form module into the library.  I think its a great addition and would probably start using it as soon as you get it released. :)

**Comment by joelbyler** [comment]
@tokafish also just to give some additional reassurance, I was able to run the example above without any issues.  The code is simple and it mimics what is already documented for the python library so I feel that's a huge win.  I think this is good as is, but if you want to add the additional functions to make this easier to use that's a bonus.  🚀

**Comment by tokafish** [comment]
Awesome! Glad it works! I'll merge this with some docs and maybe do a DSL later

**Pull request merged**
